import { ENV } from "./env.js";

export const IDS = {
  SHOP_CHANNEL_ID: ENV.SHOP_CHANNEL_ID,
  QUEUE_CHANNEL_ID: ENV.QUEUE_CHANNEL_ID,
  LOG_CHANNEL_ID: ENV.LOG_CHANNEL_ID,
  VIP_LOG_CHANNEL_ID: ENV.VIP_LOG_CHANNEL_ID,
  SLIP_ARCHIVE_CHANNEL_ID: ENV.SLIP_ARCHIVE_CHANNEL_ID,
  VEHICLE_PLATE_LOG_CHANNEL_ID: ENV.VEHICLE_PLATE_LOG_CHANNEL_ID,

  ADMIN_ROLE_ID: ENV.ADMIN_ROLE_ID,

  ADMIN_DASHBOARD_CHANNEL_ID: ENV.ADMIN_DASHBOARD_CHANNEL_ID,
  ADMIN_DASHBOARD_MESSAGE_ID: ENV.ADMIN_DASHBOARD_MESSAGE_ID,

  VIP_BASIC_ROLE_ID: ENV.VIP_BASIC_ROLE_ID,
  VIP_PRO_ROLE_ID: ENV.VIP_PRO_ROLE_ID,
  VIP_ELITE_ROLE_ID: ENV.VIP_ELITE_ROLE_ID,

  TICKET_CATEGORY_ID: ENV.TICKET_CATEGORY_ID,
};
